// packages/vue/src/App.vue
<template>
    <div>
        <h1>Vue</h1>
        <UserList v-bind:users="users" />
        <LoadButton v-bind:onUserLoad="onUserLoad" />
    </div>
</template>

<script>
import UserList from './components/UserList.vue';
import LoadButton from './components/LoadButton.vue';

export default {
    name: 'app',
    components: {
        UserList,
        LoadButton,
    },
    data: () => ({
        users: [],
    }),
    methods: {
        onUserLoad(user) {
            this.users.push(user);
        },
    },
};
</script>

<style>
</style>

// packages/crank/src/App.jsx
/** @jsx createElement */
import { createElement } from '@bikeshaving/crank';

import UserList from './components/UserList';
import LoadButton from './components/LoadButton';

export default function* App() {
    let users = [];

    const addUser = user => {
        users.push(user);
        this.refresh();
    };

    while (true)
        yield (
            <div>
                <h1>Crank</h1>
                <UserList users={users} />
                <LoadButton onUserLoad={addUser} />
            </div>
        );
}
