// packages/vue/src/components/UserList.vue
<template>
    <ul class="user-list">
        <li v-for="(user) in users" v-bind:key="user.name">{{ user.name }} : {{ user.email }}</li>
    </ul>
</template>

<script>
export default {
    name: 'UserList',
    props: {
        users: Array,
    },
};
</script>

<style>
.user-list li {
    margin-top: 0.5rem;
}
</style>

// packages/svelte/src/UserList.svelte
<script>
    import { users } from './store.js';

    let _users = []; // TODO is local variable really required

    users.subscribe(users => {
        _users = users;
    })
</script>

<style>
    li {
        margin-top: .5rem;
    }
</style>

<ul>
    {#each _users as user}
        <li>{user.name} : {user.email}</li>
    {/each}
</ul>
