// packages/vue/src/components/UserList.vue
<template>
    <ul class="user-list">
        <li v-for="(user) in users" v-bind:key="user.name">{{ user.name }} : {{ user.email }}</li>
    </ul>
</template>

<script>
export default {
    name: 'UserList',
    props: {
        users: Array,
    },
};
</script>

<style>
.user-list li {
    margin-top: 0.5rem;
}
</style>

// packages/crank/src/components/UserList.jsx
/** @jsx createElement */
import { createElement } from '@bikeshaving/crank';

const UserList = ({ users }) => (
    <ul className='user-list'>
        {users.map(({ name, email }) => (
            <li key={name}>
                {name} : {email}
            </li>
        ))}
    </ul>
);

export default UserList;
