// packages/react/src/App.jsx
import React, { useReducer } from 'react';

import UserList from './components/UserList';
import LoadButton from './components/LoadButton';

const App = () => {
    const [users, addUser] = useReducer((prev, next) => [...prev, next], []);

    return (
        <>
            <h1>React</h1>
            <UserList users={users} />
            <LoadButton onUserLoad={addUser} />
        </>
    );
};

export default App;

// packages/vue/src/App.vue
<template>
    <div>
        <h1>Vue</h1>
        <UserList v-bind:users="users" />
        <LoadButton v-bind:onUserLoad="onUserLoad" />
    </div>
</template>

<script>
import UserList from './components/UserList.vue';
import LoadButton from './components/LoadButton.vue';

export default {
    name: 'app',
    components: {
        UserList,
        LoadButton,
    },
    data: () => ({
        users: [],
    }),
    methods: {
        onUserLoad(user) {
            this.users.push(user);
        },
    },
};
</script>

<style>
</style>
