// packages/react/src/components/LoadButton.jsx
import React, { useReducer } from 'react';

const LoadButton = ({ onUserLoad }) => {
    const [userIndex, increaseUserIndex] = useReducer(s => s + 1, 1);
    const [disabled, toggleDisabled] = useReducer(s => !s, false);

    const onClick = () => {
        toggleDisabled();
        increaseUserIndex();

        fetch(`https://jsonplaceholder.typicode.com/users/${userIndex}`)
            .then(response => response.json())
            .then(onUserLoad)
            .then(toggleDisabled);
    };

    return (
        <button onClick={onClick} disabled={disabled} className='load-button'>
            Load next user
        </button>
    );
};

export default LoadButton;

// packages/vue/src/components/LoadButton.vue
<template>
    <button v-bind:disabled="disabled" class="load-button" v-on:click="onClick">Load next user</button>
</template>

<script>
let userIndex = 1;

export default {
    name: 'LoadButton',
    props: {
        onUserLoad: Function,
    },
    data: () => ({
        disabled: false,
    }),
    methods: {
        toggleDisabled() {
            this.disabled = !this.disabled;
        },
        onClick() {
            this.toggleDisabled();

            fetch(`https://jsonplaceholder.typicode.com/users/${userIndex++}`)
                .then(response => response.json())
                .then(this.onUserLoad)
                .then(this.toggleDisabled);
        },
    },
};
</script>

<style scoped>
.load-button {
    font-family: monospace;
    font-weight: 600;
    cursor: pointer;
    color: white;
    background-color: black;
    height: 2rem;
    width: 10rem;
    border-radius: 0.75rem;
    border: 1px solid white;
    box-shadow: 0 0.1rem 0.5rem #000;
    outline: 0;
}

.load-button:active {
    transform: scale(0.9);
}

.load-button[disabled] {
    color: grey;
}
</style>
